version: 2
jobs:
  build:
    working_directory: ~/leiningen
    docker:
      # somehow docker hub deleted the 2.8.1 image?!
      # https://circleci.com/gh/technomancy/leiningen/1584
      - image: clojure:lein-2.8.0
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run:
          working_directory: ~/leiningen/leiningen-core
          command: lein bootstrap
      # Use port 80 keyserver pool to work around fragile connectivity in GPG tests.
      - run: mkdir -p ~/.gnupg && echo 'keyserver hkp://p80.pool.sks-keyservers.net:80' >> ~/.gnupg/dirmngr.conf
      - run: bin/lein test
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>

